
GET http://localhost:3001/
###

GET http://localhost:3001/api/products


###


GET http://localhost:3001/api/v1/notes


###


POST http://localhost:3001/api/auth/register
content-type: application/json

{
    "name":"ankit01",
    "email":"ankit01@gmail.com",
    "password":"12345678"
}

###


POST http://localhost:3001/user
content-type: application/json

{
    "name": "Ankit",
    "email":"ankitkaushik@gmail.com",
    "password": "1011"

}

//to check the creditianls of the user with email and user
### 
POST http://localhost:3001/api/auth/login
content-type: application/json

{
   "email":"ankitkaushik@gmail.com",
   "password":"1011"
}


###

POST http://localhost:3001/product
content-type: application/json

{
    "name": "abc",
    "description":"the ai product description",
    "icon": "httplink",
    "url":"gsufhasifhis",
    "shortDesc":"dghfahgduvbatyvffx",
    "createdBy":"6453496b393b6edce1cef163",
    "updatedBy":"6453496b393b6edce1cef163"
}
